# Generated by Django 5.1.5 on 2025-01-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='calories',
            new_name='kcal',
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
